on:
  push:
    branches:
      - develop
name: integration tests
jobs:
  integration-tests:
    name: Release
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        go: ['1.13']
    steps:    
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
        id: go
      - name: Check out code
        uses: actions/checkout@master
      - name: Integration tests
        env:
          DISGORD_TOKEN_INTEGRATION_TEST: ${{ secrets.DISGORD_TOKEN_INTEGRATION_TEST }}
        run: go test ./... -race -tags=integration
